name: dedsec_ui
description: Dedsec_BR UI — pop-art / glitch / cyberpunk civic app design system.
version: 0.0.1
homepage:

resolution: workspace
environment:
  sdk: ^3.11.5
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
